//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogsItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogsItem()
        {
            this.UserLogs = new HashSet<UserLog>();
        }
    
        public int ID { get; set; }
        public Nullable<int> dayID { get; set; }
        public Nullable<int> logID { get; set; }
        public Nullable<bool> Morning { get; set; }
        public Nullable<bool> Afternoon { get; set; }
        public Nullable<bool> Evening { get; set; }
    
        public virtual DaysOfWeek DaysOfWeek { get; set; }
        public virtual LogsLkp LogsLkp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLog> UserLogs { get; set; }
    }
}
