//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeInOut
    {
        public int Id { get; set; }
        public Nullable<int> fk_TimeSheetId { get; set; }
        public string TimeIn { get; set; }
        public Nullable<bool> isInAM { get; set; }
        public string TimeOut { get; set; }
        public Nullable<bool> isOutAM { get; set; }
        public Nullable<int> fk_serviceCode { get; set; }
        public Nullable<int> fk_plansection { get; set; }
        public Nullable<System.DateTime> dayDate { get; set; }
        public string TimeIn2 { get; set; }
        public string TimeOut2 { get; set; }
        public Nullable<bool> isInAM2 { get; set; }
        public Nullable<bool> isOutAM2 { get; set; }
    
        public virtual TimeSheet TimeSheet { get; set; }
        public virtual serviceCode serviceCode { get; set; }
        public virtual planSection planSection { get; set; }
    }
}
