//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeSheet()
        {
            this.TimeInOuts = new HashSet<TimeInOut>();
        }
    
        public int Id { get; set; }
        public string fk_userId { get; set; }
        public Nullable<System.DateTime> DayDate { get; set; }
        public Nullable<bool> isBackup { get; set; }
        public Nullable<bool> isLiveIn { get; set; }
        public Nullable<int> fk_statusid { get; set; }
        public Nullable<bool> HasTime2 { get; set; }
        public Nullable<bool> isDraft { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeInOut> TimeInOuts { get; set; }
        public virtual status status { get; set; }
    }
}
