//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toileting
    {
        public int ID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<bool> Urine { get; set; }
        public Nullable<bool> Bm { get; set; }
        public string UrineTime { get; set; }
        public string BmTime { get; set; }
        public int DayID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual DaysOfWeek DaysOfWeek { get; set; }
    }
}
