//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int ID { get; set; }
        public string empID { get; set; }
        public int logItemID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual LogsItem LogsItem { get; set; }
    }
}
