//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Logs
    {
        public string logTypeName { get; set; }
        public int LgTypeID { get; set; }
        public int LogsTypesID { get; set; }
        public string LogName { get; set; }
        public string dayName { get; set; }
        public bool HasMorning { get; set; }
        public bool HasAfternoon { get; set; }
        public bool HasEvening { get; set; }
        public bool isSwapped { get; set; }
        public Nullable<int> categoryID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> CtgryID { get; set; }
        public Nullable<int> LogTypeID { get; set; }
        public int ID { get; set; }
        public Nullable<bool> Morning { get; set; }
        public Nullable<bool> Afternoon { get; set; }
        public Nullable<bool> Evening { get; set; }
        public int logLkpID { get; set; }
    }
}
